In [5]:
import pandas as pd
df=pd.read_csv("Dataset 2.csv")
df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

In [6]:
print("Shape:",df.shape)

Shape: (750, 10)

In [7]:
print("Column Names\n")
print(df.columns)

Column Names

Index(['UserID', 'Age', 'Gender', 'SubscriptionType', 'WatchHoursPerWeek',
       'DevicesUsed', 'FavoriteGenre', 'AdClicks', 'MonthlySpend',
       'SubscriptionRenewed'],
      dtype='object')

In [8]:
print(df.dtypes)

UserID                  int64
Age                     int64
Gender                 object
SubscriptionType       object
WatchHoursPerWeek       int64
DevicesUsed             int64
FavoriteGenre          object
AdClicks                int64
MonthlySpend            int64
SubscriptionRenewed    object
dtype: object

In [9]:
df.isnull()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
745,False,False,False,False,False,False,False,False,False,False
746,False,False,False,False,False,False,False,False,False,False
747,False,False,False,False,False,False,False,False,False,False
748,False,False,False,False,False,False,False,False,False,False
749,False,False,False,False,False,False,False,False,False,False

In [10]:
print("Average:",df['Age'].mean())
print("Watch hours:",df['WatchHoursPerWeek'].mean())
print("Monthly spending:",df['MonthlySpend'].mean())
print("Number of users:",df['SubscriptionType'].value_counts())
percentage_active=(df['SubscriptionRenewed']=='Yes').mean()*100
print("Percentage:",percentage_active)

Average: 41.824
Watch hours: 14.236
Monthly spending: 689.9053333333334
Number of users: SubscriptionType
Basic      342
Premium    279
VIP        129
Name: count, dtype: int64
Percentage: 46.266666666666666

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['SubscriptionType']=le.fit_transform(df['SubscriptionType'])
df['FavoriteGenre']=le.fit_transform(df['FavoriteGenre'])
df['SubscriptionRenewed']=le.fit_transform(df['SubscriptionRenewed'])

In [12]:
from sklearn.model_selection import train_test_split
X=df.drop(['UserID','Age','Gender','SubscriptionRenewed'],axis=1)
y=df['SubscriptionRenewed']
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
    )

In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
dt=DecisionTreeClassifier(random_state=42)
dt.fit(X_train,y_train)
pred=dt.predict(X_test)
print(accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))

0.5133333333333333
[[43 39]
 [34 34]]

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
knn_pred=knn.predict(X_test)
print("Accuracy:",accuracy_score(y_test,knn_pred))

Accuracy: 0.56

In [18]:
from sklearn.linear_model import LinearRegression
X_reg=df.drop(['UserID','Age','Gender','MonthlySpend'],axis=1)
y_reg=df['MonthlySpend']
X_train_reg,X_test_reg,y_train_reg,y_test_reg=train_test_split(
    X_reg,y_reg,test_size=0.2,random_state=42
)
lr=LinearRegression()
lr.fit(X_train_reg,y_train_reg)
amount=lr.predict([[1,34,2,1,17,1]])
print("Predicted spending:",amount[0])

Predicted spending: 921.141506776966

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

1 SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend

2 It predicts a small number of outputs

3 It gives a numeric answer

4 K-Nearest Neighbors

5 Promoting to a particular age group or gender which has greater monthly spending